/* fusion-opc.c -- Definitions for moxie opcodes.
   Copyright (C) 2009-2017 Free Software Foundation, Inc.
   Contributed by Dylan Wadler

   This file is part of the GNU opcodes library.

   This library is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3, or (at your option)
   any later version.

   It is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
   License for more details.

   You should have received a copy of the GNU General Public License
   along with this file; see the file COPYING.  If not, write to the
   Free Software Foundation, 51 Franklin Street - Fifth Floor, Boston,
   MA 02110-1301, USA.  */

#include "sysdep.h"
#include "opcode/fusion.h"

//Uses ALU OP field to determine
const fusion_opc_info_t fusion_insn_R[NUM_INSN_R] = {
/*   Name  ALUOP	args		frmt		cpid	imm_mask	opc	  	*/
	{"add", 0x00	USE_RDAB,	FRMT_R,			},
	{"sub", 0x01, 	USE_RDAB,		},
	{0x02,	USE_RDAB,		"addu"},
	{0x03,	USE_RDAB,		"subu"},
	{0x04,	USE_RDAB,		"tcmp"},
	{0x05,	USE_RDAB,		"and"},
	{0x06,	USE_RDAB,		"or"},
	{0x07,	USE_RDAB,		"xor"},
	{0x08,	USE_RDAB,		"sal"},
	{0x09,	USE_RDAB,		"sar"},
	{0x0a,	USE_RDAB,		"sll"},
	{0x0b,	USE_RDAB,		"slr"},
	{0x0c,	USE_RDAB,		"comp"},
	{0x0d,	USE_RDAB,		"nri"},
	{0x0e,	USE_RDAB,		"nri"},
	{0x0f,	USE_RDAB,		"nri"}
};

const fusion_insn_t fusion_insn_I[NUM_INSN_I] = {
	/*ALUOP	Frmt			Name	*/
	{0x00, 	USE_RDAI,		"addi"},
	{0x01, 	USE_RDAI,		"subi"},
	{0x02,	USE_RDAI,		"addui"},
	{0x03,	USE_RDAI,		"subui"},
	{0x04,	USE_RDAI,		"nri"},
	{0x05,	USE_RDAI,		"andi"},
	{0x06,	USE_RDAI,		"ori"},
	{0x07,	USE_RDAI,		"xori"},
	{0x08,	USE_RDAI,		"sali"},
	{0x09,	USE_RDAI,		"sari"},
	{0x0a,	USE_RDAI,		"slli"},
	{0x0b,	USE_RDAI,		"slri"},
	{0x0c,	USE_RDAI,		"compi"},
	{0x0d,	USE_RDAI,		"nri"},
	{0x0e,	USE_RDAI,		"nri"},
	{0x0f,	USE_RDAI,		"nri"}
};
const fusion_insn_t fusion_insn_L[NUM_INSN_L] = {
	/*Funct	FRMT			Name*/
	{0x0, 	USE_RDAI,		"lw"},
	{0x1,	USE_RDAI,		"lh"},
	{0x2,	USE_RDAI,		"lth"},
	{0x3,	USE_RDAI,		"lb"}

};
const fusion_insn_t fusion_insn_LI[NUM_INSN_LI] = {
	/*DSEL	Frmt			Name*/
	{0x0,	USE_RDI,		"li"},
	{0x1,	USE_RDI,		"lsi"},
	{0x2,	USE_RDI,		"lgi"},
	{0x3,	USE_RDI,		"lui"},
	{0x4,	USE_RDI,		"lusi"},
	{0x5,	USE_RDI,		"lugi"},
	{0x6,	USE_RDI,		"nri"},
	{0x7,	USE_RDI,		"nri"},
	{0x8,	USE_RDI,		"lni"},
	{0x9,	USE_RDI,		"lnsi"},
	{0xa,	USE_RDI,		"lngi"},
	{0xb,	USE_RDI,		"luni"},
	{0xc,	USE_RDI,		"lunsi"},
	{0xd,	USE_RDI,		"lungi"},
	{0xe,	USE_RDI,		"nri"},
	{0xf,	USE_RDI,		"nri"},
};
const fusion_insn_t fusion_insn_S[NUM_INSN_S] = {
	/*FUNCT	Frmt			Name*/
	{0x0, 	USE_RABI,		"sw"},
	{0x1,	USE_RABI,		"sh"},
	{0x2,	USE_RABI,		"sth"},
	{0x3,	USE_RABI,		"sb"}
};
const fusion_insn_t fusion_insn_J[NUM_INSN_J] = {
/*USESREG	Frmt			Name*/
	{0x0,	USE_RAI,		"j"},
	{0x1,	USE_RAI,		"jr"}
};
const fusion_insn_t fusion_insn_JL[NUM_INSN_JL] = {
/*USESREG	Frmt			Name*/
	{0x0,	USE_RAI,		"jal"},
	{0x1,	USE_RAI,		"jrl"}
};
const fusion_insn_t fusion_insn_B[NUM_INSN_B] = {
	/*Funct	Frmt			Name*/
	{0x0,	USE_RABI,		"beq"},
	{0x1,	USE_RABI,		"bne"},
	{0x2,	USE_RABI,		"bgt"},
	{0x3,	USE_RABI,		"blt"}

};
const fusion_insn_t fusion_insn_SYS[NUM_INSN_SYS] = {
	{0x00,	USE_RDAI,		"syscall"},
	{0x01,	USE_RDAI,		"sysret"},
	{0x02,	USE_RDA,		"stspr"},
	{0x03,	USE_RDA,		"ldspr"},
	{0x04,	USE_NONE,		"sync"},
	{0x05,	USE_I,			"pmir"},
	{0x06, 	USE_I,			"pmd"},
	{0x07,	USE_NONE,		"nri"},
	{0x08,	USE_NONE,		"nri"},
	{0x09,	USE_NONE,		"nri"},
	{0x0a,	USE_NONE,		"nri"},
	{0x0b,	USE_NONE,		"nri"},
	{0x0c,	USE_NONE,		"nri"},
	{0x0d,	USE_NONE,		"nri"},
	{0x0e,	USE_NONE,		"nri"},
	{0x0f,	USE_NONE,		"nri"},
	{0x10,	USE_NONE,		"nri"},
	{0x11,	USE_NONE,		"nri"},
	{0x12,	USE_NONE,		"nri"},
	{0x13,	USE_NONE,		"nri"},
	{0x14,	USE_NONE,		"nri"},
	{0x15,	USE_NONE,		"nri"},
	{0x16,	USE_NONE,		"nri"},
	{0x17,	USE_NONE,		"nri"},
	{0x18,	USE_NONE,		"nri"},
	{0x19,	USE_NONE,		"nri"},
	{0x1a,	USE_NONE,		"nri"},
	{0x1b,	USE_NONE,		"nri"},
	{0x1c,	USE_NONE,		"nri"},
	{0x1d,	USE_NONE,		"nri"},
	{0x1e,	USE_NONE,		"nri"},
	{0x1f,	USE_NONE,		"nri"},
	{0x20,	USE_NONE,		"nri"},
	{0x21,	USE_NONE,		"nri"},
	{0x22,	USE_NONE,		"nri"},
	{0x23,	USE_NONE,		"nri"},
	{0x24,	USE_NONE,		"nri"},
	{0x25,	USE_NONE,		"nri"},
	{0x26,	USE_NONE,		"nri"},
	{0x27,	USE_NONE,		"nri"},
	{0x28,	USE_NONE,		"nri"},
	{0x29,	USE_NONE,		"nri"},
	{0x2a,	USE_NONE,		"nri"},
	{0x2b,	USE_NONE,		"nri"},
	{0x2c,	USE_NONE,		"nri"},
	{0x2d,	USE_NONE,		"nri"},
	{0x2e,	USE_NONE,		"nri"},
	{0x2f,	USE_NONE,		"nri"},
	{0x30,	USE_NONE,		"nri"},
	{0x31,	USE_NONE,		"nri"},
	{0x32,	USE_NONE,		"nri"},
	{0x33,	USE_NONE,		"nri"},
	{0x34,	USE_NONE,		"nri"},
	{0x35,	USE_NONE,		"nri"},
	{0x36,	USE_NONE,		"nri"},
	{0x37,	USE_NONE,		"nri"},
	{0x38,	USE_NONE,		"nri"},
	{0x39,	USE_NONE,		"nri"},
	{0x3a,	USE_NONE,		"nri"},
	{0x3b,	USE_NONE,		"nri"},
	{0x3c,	USE_NONE,		"nri"},
	{0x3d,	USE_NONE,		"nri"},
	{0x3e,	USE_NONE,		"nri"},
	{0x3f,	USE_NONE,		"nri"},
	{0x40,	USE_NONE,		"nri"},
	{0x41,	USE_NONE,		"nri"},
	{0x42,	USE_NONE,		"nri"},
	{0x43,	USE_NONE,		"nri"},
	{0x44,	USE_NONE,		"nri"},
	{0x45,	USE_NONE,		"nri"},
	{0x46,	USE_NONE,		"nri"},
	{0x47,	USE_NONE,		"nri"},
	{0x48,	USE_NONE,		"nri"},
	{0x49,	USE_NONE,		"nri"},
	{0x4a,	USE_NONE,		"nri"},
	{0x4b,	USE_NONE,		"nri"},
	{0x4c,	USE_NONE,		"nri"},
	{0x4d,	USE_NONE,		"nri"},
	{0x4e,	USE_NONE,		"nri"},
	{0x4f,	USE_NONE,		"nri"},
	{0x50,	USE_NONE,		"nri"},
	{0x51,	USE_NONE,		"nri"},
	{0x52,	USE_NONE,		"nri"},
	{0x53,	USE_NONE,		"nri"},
	{0x54,	USE_NONE,		"nri"},
	{0x55,	USE_NONE,		"nri"},
	{0x56,	USE_NONE,		"nri"},
	{0x57,	USE_NONE,		"nri"},
	{0x58,	USE_NONE,		"nri"},
	{0x59,	USE_NONE,		"nri"},
	{0x5a,	USE_NONE,		"nri"},
	{0x5b,	USE_NONE,		"nri"},
	{0x5c,	USE_NONE,		"nri"},
	{0x5d,	USE_NONE,		"nri"},
	{0x5e,	USE_NONE,		"nri"},
	{0x5f,	USE_NONE,		"nri"},
	{0x60,	USE_NONE,		"nri"},
	{0x61,	USE_NONE,		"nri"},
	{0x62,	USE_NONE,		"nri"},
	{0x63,	USE_NONE,		"nri"},
	{0x64,	USE_NONE,		"nri"},
	{0x65,	USE_NONE,		"nri"},
	{0x66,	USE_NONE,		"nri"},
	{0x67,	USE_NONE,		"nri"},
	{0x68,	USE_NONE,		"nri"},
	{0x69,	USE_NONE,		"nri"},
	{0x6a,	USE_NONE,		"nri"},
	{0x6b,	USE_NONE,		"nri"},
	{0x6c,	USE_NONE,		"nri"},
	{0x6d,	USE_NONE,		"nri"},
	{0x6e,	USE_NONE,		"nri"},
	{0x6f,	USE_NONE,		"nri"},
	{0x70,	USE_NONE,		"nri"},
	{0x71,	USE_NONE,		"nri"},
	{0x72,	USE_NONE,		"nri"},
	{0x73,	USE_NONE,		"nri"},
	{0x74,	USE_NONE,		"nri"},
	{0x75,	USE_NONE,		"nri"},
	{0x76,	USE_NONE,		"nri"},
	{0x77,	USE_NONE,		"nri"},
	{0x78,	USE_NONE,		"nri"},
	{0x79,	USE_NONE,		"nri"},
	{0x7a,	USE_NONE,		"nri"},
	{0x7b,	USE_NONE,		"nri"},
	{0x7c,	USE_NONE,		"nri"},
	{0x7d,	USE_NONE,		"nri"},
	{0x7e,	USE_NONE,		"nri"},
	{0x7f,	USE_NONE,		"nri"},
	{0x80,	USE_NONE,		"nri"},
	{0x81,	USE_NONE,		"nri"},
	{0x82,	USE_NONE,		"nri"},
	{0x83,	USE_NONE,		"nri"},
	{0x84,	USE_NONE,		"nri"},
	{0x85,	USE_NONE,		"nri"},
	{0x86,	USE_NONE,		"nri"},
	{0x87,	USE_NONE,		"nri"},
	{0x88,	USE_NONE,		"nri"},
	{0x89,	USE_NONE,		"nri"},
	{0x8a,	USE_NONE,		"nri"},
	{0x8b,	USE_NONE,		"nri"},
	{0x8c,	USE_NONE,		"nri"},
	{0x8d,	USE_NONE,		"nri"},
	{0x8e,	USE_NONE,		"nri"},
	{0x8f,	USE_NONE,		"nri"},
	{0x90,	USE_NONE,		"nri"},
	{0x91,	USE_NONE,		"nri"},
	{0x92,	USE_NONE,		"nri"},
	{0x93,	USE_NONE,		"nri"},
	{0x94,	USE_NONE,		"nri"},
	{0x95,	USE_NONE,		"nri"},
	{0x96,	USE_NONE,		"nri"},
	{0x97,	USE_NONE,		"nri"},
	{0x98,	USE_NONE,		"nri"},
	{0x99,	USE_NONE,		"nri"},
	{0x9a,	USE_NONE,		"nri"},
	{0x9b,	USE_NONE,		"nri"},
	{0x9c,	USE_NONE,		"nri"},
	{0x9d,	USE_NONE,		"nri"},
	{0x9e,	USE_NONE,		"nri"},
	{0x9f,	USE_NONE,		"nri"},
	{0xa0,	USE_NONE,		"nri"},
	{0xa1,	USE_NONE,		"nri"},
	{0xa2,	USE_NONE,		"nri"},
	{0xa3,	USE_NONE,		"nri"},
	{0xa4,	USE_NONE,		"nri"},
	{0xa5,	USE_NONE,		"nri"},
	{0xa6,	USE_NONE,		"nri"},
	{0xa7,	USE_NONE,		"nri"},
	{0xa8,	USE_NONE,		"nri"},
	{0xa9,	USE_NONE,		"nri"},
	{0xaa,	USE_NONE,		"nri"},
	{0xab,	USE_NONE,		"nri"},
	{0xac,	USE_NONE,		"nri"},
	{0xad,	USE_NONE,		"nri"},
	{0xae,	USE_NONE,		"nri"},
	{0xaf,	USE_NONE,		"nri"},
	{0xb0,	USE_NONE,		"nri"},
	{0xb1,	USE_NONE,		"nri"},
	{0xb2,	USE_NONE,		"nri"},
	{0xb3,	USE_NONE,		"nri"},
	{0xb4,	USE_NONE,		"nri"},
	{0xb5,	USE_NONE,		"nri"},
	{0xb6,	USE_NONE,		"nri"},
	{0xb7,	USE_NONE,		"nri"},
	{0xb8,	USE_NONE,		"nri"},
	{0xb9,	USE_NONE,		"nri"},
	{0xba,	USE_NONE,		"nri"},
	{0xbb,	USE_NONE,		"nri"},
	{0xbc,	USE_NONE,		"nri"},
	{0xbd,	USE_NONE,		"nri"},
	{0xbe,	USE_NONE,		"nri"},
	{0xbf,	USE_NONE,		"nri"},
	{0xc0,	USE_NONE,		"nri"},
	{0xc1,	USE_NONE,		"nri"},
	{0xc2,	USE_NONE,		"nri"},
	{0xc3,	USE_NONE,		"nri"},
	{0xc4,	USE_NONE,		"nri"},
	{0xc5,	USE_NONE,		"nri"},
	{0xc6,	USE_NONE,		"nri"},
	{0xc7,	USE_NONE,		"nri"},
	{0xc8,	USE_NONE,		"nri"},
	{0xc9,	USE_NONE,		"nri"},
	{0xca,	USE_NONE,		"nri"},
	{0xcb,	USE_NONE,		"nri"},
	{0xcc,	USE_NONE,		"nri"},
	{0xcd,	USE_NONE,		"nri"},
	{0xce,	USE_NONE,		"nri"},
	{0xcf,	USE_NONE,		"nri"},
	{0xd0,	USE_NONE,		"nri"},
	{0xd1,	USE_NONE,		"nri"},
	{0xd2,	USE_NONE,		"nri"},
	{0xd3,	USE_NONE,		"nri"},
	{0xd4,	USE_NONE,		"nri"},
	{0xd5,	USE_NONE,		"nri"},
	{0xd6,	USE_NONE,		"nri"},
	{0xd7,	USE_NONE,		"nri"},
	{0xd8,	USE_NONE,		"nri"},
	{0xd9,	USE_NONE,		"nri"},
	{0xda,	USE_NONE,		"nri"},
	{0xdb,	USE_NONE,		"nri"},
	{0xdc,	USE_NONE,		"nri"},
	{0xdd,	USE_NONE,		"nri"},
	{0xde,	USE_NONE,		"nri"},
	{0xdf,	USE_NONE,		"nri"},
	{0xe0,	USE_NONE,		"nri"},
	{0xe1,	USE_NONE,		"nri"},
	{0xe2,	USE_NONE,		"nri"},
	{0xe3,	USE_NONE,		"nri"},
	{0xe4,	USE_NONE,		"nri"},
	{0xe5,	USE_NONE,		"nri"},
	{0xe6,	USE_NONE,		"nri"},
	{0xe7,	USE_NONE,		"nri"},
	{0xe8,	USE_NONE,		"nri"},
	{0xe9,	USE_NONE,		"nri"},
	{0xea,	USE_NONE,		"nri"},
	{0xeb,	USE_NONE,		"nri"},
	{0xec,	USE_NONE,		"nri"},
	{0xed,	USE_NONE,		"nri"},
	{0xee,	USE_NONE,		"nri"},
	{0xef,	USE_NONE,		"nri"},
	{0xf0,	USE_NONE,		"nri"},
	{0xf1,	USE_NONE,		"nri"},
	{0xf2,	USE_NONE,		"nri"},
	{0xf3,	USE_NONE,		"nri"},
	{0xf4,	USE_NONE,		"nri"},
	{0xf5,	USE_NONE,		"nri"},
	{0xf6,	USE_NONE,		"nri"},
	{0xf7,	USE_NONE,		"nri"},
	{0xf8,	USE_NONE,		"nri"},
	{0xf9,	USE_NONE,		"nri"},
	{0xfa,	USE_NONE,		"nri"},
	{0xfb,	USE_NONE,		"nri"},
	{0xfc,	USE_NONE,		"nri"},
	{0xfd,	USE_NONE,		"nri"},
	{0xfe,	USE_NONE,		"nri"},
	{0xff,	USE_NONE,		"nri"},
};
