SCRIPT_NAME=elf
ARCH=fusion
TEMPLATE_NAME=elf32
#TEMPLATE_NAME=generic
#EXTRA_EM_FILE=genelf
ELFSIZE=32
OUTPUT_FORMAT="elf32-fusion"
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
COMMONPAGESIZE="CONSTANT (COMMONPAGESIZE)"
TEXT_START_ADDR=0x10000
DATA_START=0x2000000
ENTRY=__start

EMBEDDED=no


